import Foundation

/// Why one cell may not be written.
///
/// A closed set of typed reasons, each carrying **the sentence the banner
/// shows**, because the two halves of a refusal have to travel together: the
/// surface greys a cell out from the reason and explains it from the same value,
/// so what the grid refuses and what the reader is told cannot drift apart. The
/// engine decides; this type is where the decision is written down in English,
/// exactly once.
///
/// The first case carries `DatabaseRowIdentityGap` rather than restating it: a
/// table's rows being unaddressable is the identity engine's verdict, and
/// re-spelling its four outcomes here would be a second vocabulary for one fact.
public enum DatabaseEditRefusal: Error, Equatable, Hashable, Sendable {
    /// The table's rows cannot be addressed one at a time — a view, a table with
    /// no usable identity, or a `WITHOUT ROWID` table whose key the page does not
    /// carry in full.
    case unaddressableRow(DatabaseRowIdentityGap)
    /// The table is addressable by rowid, but *this* row arrived without its
    /// identity value — a page composed or split as though it carried none. The
    /// row on screen cannot be named, so nothing is sent.
    case rowIdentityMissing
    /// The grid column's name matches no schema column, or matches more than one.
    /// A guess here would put the wrong column in a `SET`, so it is refused
    /// (decision 4).
    case columnNotMatched(name: String)
    /// The column is generated or hidden. SQLite computes it; an `UPDATE` naming
    /// it is an error, and one that succeeded would be worse.
    case generatedColumn(name: String)
    /// The cell holds a blob. A page carries a blob's *length* and never its
    /// bytes, so the old value cannot be put in a `WHERE` — there is nothing to
    /// compare with — and a text editor is not how a blob is replaced.
    case blobCell(column: String)
    /// The cell is not on the page at all: the row or the column is out of range
    /// for what the grid published. A race between a page turn and a commit,
    /// refused rather than mis-addressed.
    case cellNotOnPage

    /// What the reader is told.
    public var message: String {
        switch self {
        case .unaddressableRow(let gap):
            return Self.message(for: gap)
        case .rowIdentityMissing:
            return "This row arrived without its row id, so it cannot be identified. Reload the table and try again."
        case .columnNotMatched(let name):
            return "The column “\(name)” has no single match in this table’s schema, so it cannot be edited."
        case .generatedColumn(let name):
            return "The column “\(name)” is generated by the database, so it cannot be edited."
        case .blobCell(let column):
            return "The cell in “\(column)” holds binary data, which this viewer shows by size and cannot edit."
        case .cellNotOnPage:
            return "That cell is no longer on this page. Reload the table and try again."
        }
    }

    private static func message(for gap: DatabaseRowIdentityGap) -> String {
        switch gap {
        case .view:
            return "This is a view. Its rows are computed by a query, so they cannot be edited here."
        case .noRowIdentity:
            return "This table declares no row id and no primary key, so a single row cannot be identified for editing."
        case .keyColumnNotAnswered(let name):
            return "This table is identified by “\(name)”, which this page does not show, so its rows cannot be edited."
        case .keyColumnAmbiguous(let name):
            return "This table is identified by “\(name)”, and this page shows more than one column of that name, "
                + "so its rows cannot be edited."
        }
    }
}

extension DatabaseEditRefusal: LocalizedError {
    public var errorDescription: String? { message }
}

/// One column of a row's address: the name the `WHERE` quotes and the value it
/// is compared against.
///
/// A named pair rather than a tuple so the address is `Equatable` and assertable
/// whole — the binding *order* is the thing a test has to be able to pin, and an
/// array of these carries it.
public struct DatabaseColumnValue: Equatable, Hashable, Sendable {
    /// The column name, as the schema declares it.
    public var name: String
    /// The value the row is known to hold there — the one the page answered.
    public var value: DatabaseValue

    public init(name: String, value: DatabaseValue) {
        self.name = name
        self.value = value
    }
}

/// How one row is named in an `UPDATE … WHERE`: the identity strategy, with the
/// values this particular row carries for it.
///
/// `DatabaseRowIdentity` says how the *table*'s rows are addressed;
/// this says how *this* row is. The split matters because the strategy is
/// resolved once per table selection while the values change with every page.
public enum DatabaseRowAddress: Equatable, Hashable, Sendable {
    /// Addressed by rowid, under this spelling, with the value the page's
    /// trailing identity column answered for this row.
    case rowid(alias: DatabaseRowIdAlias, value: DatabaseValue)
    /// Addressed by the declared primary key: every key column, **in key
    /// order**, with the value the page answered for it.
    case primaryKey([DatabaseColumnValue])
}

/// What it takes to write one cell of one table: the finished statement and how
/// many rows it must change.
///
/// `requiredAffectedRows` is always 1 and is carried anyway rather than assumed
/// downstream, because it is the whole safety property: the write runs inside a
/// transaction that **commits only when the count matches**, so a `WHERE` that
/// named no row (the row changed underneath the reader) or several (an
/// identity that turned out not to identify) is rolled back rather than
/// explained afterwards. The number travels with the statement so the app half
/// compares it without knowing what it means.
public struct DatabaseUpdatePlan: Equatable, Sendable {
    /// The `UPDATE`, with every value bound.
    public var statement: DatabaseStatement
    /// How many rows the statement must change for the transaction to commit.
    public var requiredAffectedRows: Int
    /// What the cell will hold — the typing rule's answer, carried so the model
    /// can say what it wrote without re-deriving it.
    public var newValue: DatabaseValue

    public init(statement: DatabaseStatement, requiredAffectedRows: Int = 1, newValue: DatabaseValue) {
        self.statement = statement
        self.requiredAffectedRows = requiredAffectedRows
        self.newValue = newValue
    }
}

/// Everything about the *table* a cell edit is planned against, gathered once
/// per selection.
///
/// The schema and the answered column names are both here, and both are needed,
/// because they are **not the same list**: `PRAGMA table_xinfo` describes hidden
/// columns that `SELECT *` does not answer, so the schema's ordinals and the
/// grid's part company as soon as a table has one. Every question this file asks
/// about "which column is this?" is therefore a lookup **by name** across the
/// two (decision 4), and no unique answer is a refusal.
public struct DatabaseEditTarget: Equatable, Sendable {
    /// The table's name, as the sidebar spells it.
    public var table: String
    /// The schema, in `PRAGMA table_xinfo` order, hidden columns included.
    public var columns: [DatabaseColumn]
    /// The column names the page answered, in grid order and **without** any
    /// trailing identity column.
    public var gridColumns: [String]
    /// How this table's rows are addressed.
    public var identity: DatabaseRowIdentity

    public init(
        table: String,
        columns: [DatabaseColumn],
        gridColumns: [String],
        identity: DatabaseRowIdentity
    ) {
        self.table = table
        self.columns = columns
        self.gridColumns = gridColumns
        self.identity = identity
    }
}

/// The pure planner: a cell, a table and what was typed become one statement or
/// one refusal.
///
/// Everything the write path decides is decided here — whether the cell may be
/// written at all, which schema column the grid column *is*, how one row is
/// named, what the typed text means as a stored value, and what the affected-row
/// count must be. Nothing in this file talks to a database, so every refusal and
/// every byte of the statement is testable without SQLite.
///
/// The surface asks `refusal(…)` on its own — that is what greys a cell out
/// before anyone types — and the planner asks it again before composing, so the
/// two can never disagree about what is editable.
public enum DatabaseUpdatePlanner {

    /// Why this cell may not be edited, or `nil` when it may.
    ///
    /// Ordered from the widest reason to the narrowest, so a reader looking at a
    /// view is told it is a view rather than told about the one column their
    /// pointer happened to be over.
    public static func refusal(
        target: DatabaseEditTarget,
        row: [DatabaseValue],
        rowIdentity: DatabaseValue?,
        columnIndex: Int
    ) -> DatabaseEditRefusal? {
        if case .unavailable(let gap) = target.identity { return .unaddressableRow(gap) }
        guard target.gridColumns.indices.contains(columnIndex), row.indices.contains(columnIndex) else {
            return .cellNotOnPage
        }
        if case .rowid = target.identity, rowIdentity == nil { return .rowIdentityMissing }

        let gridName = target.gridColumns[columnIndex]
        guard let schemaColumn = schemaColumn(named: gridName, in: target.columns) else {
            return .columnNotMatched(name: gridName)
        }
        if schemaColumn.isHidden { return .generatedColumn(name: schemaColumn.name) }
        if case .blob = row[columnIndex] { return .blobCell(column: schemaColumn.name) }
        return nil
    }

    /// The statement that writes `entry` into one cell, or why it may not be
    /// written.
    ///
    /// - Parameters:
    ///   - target: the table, its schema, the answered column names and how its
    ///     rows are addressed.
    ///   - row: the row as the grid shows it — **without** any trailing identity
    ///     column, so `columnIndex` indexes it directly.
    ///   - rowIdentity: the value the page's trailing identity column answered
    ///     for this row, or `nil` where the page carried none.
    ///   - columnIndex: the grid column being edited, zero-based.
    ///   - entry: what the reader typed, or the explicit NULL gesture.
    public static func plan(
        target: DatabaseEditTarget,
        row: [DatabaseValue],
        rowIdentity: DatabaseValue?,
        columnIndex: Int,
        entry: DatabaseCellEntry
    ) -> Result<DatabaseUpdatePlan, DatabaseEditRefusal> {
        if let refusal = refusal(target: target, row: row, rowIdentity: rowIdentity, columnIndex: columnIndex) {
            return .failure(refusal)
        }
        let gridName = target.gridColumns[columnIndex]
        guard let schemaColumn = schemaColumn(named: gridName, in: target.columns) else {
            return .failure(.columnNotMatched(name: gridName))
        }
        guard let address = address(target: target, row: row, rowIdentity: rowIdentity) else {
            return .failure(.unaddressableRow(.noRowIdentity))
        }

        let previousValue = row[columnIndex]
        let newValue = entry.value(
            affinity: DatabaseTypeAffinity(declaredType: schemaColumn.declaredType),
            previousValue: previousValue
        )
        let statement = DatabaseQuery.update(
            table: target.table,
            column: schemaColumn.name,
            identity: address,
            newValue: newValue,
            previousValue: previousValue
        )
        return .success(DatabaseUpdatePlan(statement: statement, newValue: newValue))
    }

    // MARK: - The two lookups

    /// The one schema column spelling `name`, or `nil` when none does or more
    /// than one does.
    ///
    /// Case-insensitively, because SQLite's identifier comparison is — and
    /// through `DatabaseRowIdentity.answeredIndex(of:in:)`, because "the same
    /// column" must mean one thing across the identity engine and this one.
    static func schemaColumn(named name: String, in columns: [DatabaseColumn]) -> DatabaseColumn? {
        guard case .found(let index) = DatabaseRowIdentity.answeredIndex(of: name, in: columns.map(\.name)) else {
            return nil
        }
        return columns[index]
    }

    /// How this row is named, given how the table's rows are addressed.
    ///
    /// `nil` where the address cannot be assembled — a key column whose value is
    /// not in the row on screen, or an empty key list. Neither can arrive from
    /// `DatabaseRowIdentity.resolve(…)`, which refuses both before a strategy is
    /// published; the guard is here so no other construction of a strategy can
    /// produce a `WHERE` that names no row and therefore matches every one.
    private static func address(
        target: DatabaseEditTarget,
        row: [DatabaseValue],
        rowIdentity: DatabaseValue?
    ) -> DatabaseRowAddress? {
        switch target.identity {
        case .rowid(let alias):
            guard let rowIdentity else { return nil }
            return .rowid(alias: alias, value: rowIdentity)
        case .primaryKey(let keyColumns):
            guard !keyColumns.isEmpty else { return nil }
            var values: [DatabaseColumnValue] = []
            for keyColumn in keyColumns {
                guard row.indices.contains(keyColumn.resultIndex) else { return nil }
                values.append(DatabaseColumnValue(name: keyColumn.name, value: row[keyColumn.resultIndex]))
            }
            return .primaryKey(values)
        case .unavailable:
            return nil
        }
    }
}
